Repository iTpple-S-POT/backend, pull requests merged in 2024-01, with the labels that each got.

#47 [FIX] user 테이블의 이름 변경
  src/main/java/org/com/itpple/spot/server/entity/User.java
Labels: bug

#48 [feat] POT 반응 추가 api 구현
  src/main/java/org/com/itpple/spot/server/common/validator/EnumValid.java
  src/main/java/org/com/itpple/spot/server/common/validator/EnumValidator.java
  src/main/java/org/com/itpple/spot/server/constant/ReactionType.java
  src/main/java/org/com/itpple/spot/server/controller/ReactionController.java
  src/main/java/org/com/itpple/spot/server/dto/reaction/request/CreateReactionRequest.java
  src/main/java/org/com/itpple/spot/server/dto/reaction/response/CreateReactionResponse.java
  src/main/java/org/com/itpple/spot/server/entity/Pot.java
  src/main/java/org/com/itpple/spot/server/entity/Reaction.java
  src/main/java/org/com/itpple/spot/server/exception/code/ErrorCode.java
  src/main/java/org/com/itpple/spot/server/exception/pot/PotIdNotFoundException.java
  src/main/java/org/com/itpple/spot/server/exception/reaction/AddMultipleReactionException.java
  src/main/java/org/com/itpple/spot/server/exception/user/UserIdNotFoundException.java
  src/main/java/org/com/itpple/spot/server/repository/ReactionRepository.java
  src/main/java/org/com/itpple/spot/server/service/ReactionService.java
  src/main/java/org/com/itpple/spot/server/service/impl/ReactionServiceImpl.java
Labels: enhancement

#49 [refactor] POT 반응 추가 API 리팩터링
  src/main/java/org/com/itpple/spot/server/common/validator/EnumValidator.java
Labels: enhancement

#55 [feat] 대댓글 작성 및 조회 API 구현
  src/main/java/org/com/itpple/spot/server/controller/CommentController.java
  src/main/java/org/com/itpple/spot/server/controller/ReactionController.java
  src/main/java/org/com/itpple/spot/server/dto/comment/CommentDto.java
  src/main/java/org/com/itpple/spot/server/dto/comment/request/CreateCommentRequest.java
  src/main/java/org/com/itpple/spot/server/dto/comment/response/CreateCommentResponse.java
  src/main/java/org/com/itpple/spot/server/entity/Comment.java
  src/main/java/org/com/itpple/spot/server/exception/code/ErrorCode.java
  src/main/java/org/com/itpple/spot/server/exception/comment/CommentPotNotMatchException.java
  src/main/java/org/com/itpple/spot/server/exception/comment/ParentCommentNotFoundException.java
  src/main/java/org/com/itpple/spot/server/repository/CommentRepository.java
  src/main/java/org/com/itpple/spot/server/service/CommentService.java
  src/main/java/org/com/itpple/spot/server/service/impl/CommentServiceImpl.java
Labels: enhancement

#61 [FEAT] pot 저장 시 userId도 함께 저장
  src/main/java/org/com/itpple/spot/server/dto/pot/request/CreatePotRequest.java
  src/main/java/org/com/itpple/spot/server/exception/code/ErrorCode.java
  src/main/java/org/com/itpple/spot/server/service/impl/PotServiceImpl.java
Labels: bug

#62 [FIX] pot 저장 시 user 및 category 제대로 저장하게 변경
  src/main/java/org/com/itpple/spot/server/dto/pot/PotDTO.java
  src/main/java/org/com/itpple/spot/server/dto/pot/request/CreatePotRequest.java
  src/main/java/org/com/itpple/spot/server/dto/pot/response/CreatePotResponse.java
  src/main/java/org/com/itpple/spot/server/entity/Pot.java
  src/main/java/org/com/itpple/spot/server/service/impl/PotServiceImpl.java
  src/test/java/org/com/itpple/spot/server/service/PotServiceTest.java
Labels: bug

#57 [feat] 유저 조회, 수정 API 구현
  src/main/java/org/com/itpple/spot/server/config/SecurityConfig.java
  src/main/java/org/com/itpple/spot/server/controller/UserInfoController.java
  src/main/java/org/com/itpple/spot/server/dto/userInfo/response/UserInfoResponse.java
  src/main/java/org/com/itpple/spot/server/service/UserInfoService.java
  src/main/java/org/com/itpple/spot/server/service/impl/UserInfoServiceImpl.java
Labels: enhancement

#63 [feat] RestControllerAdvice로 에러 처리 할 때 log에 남기기
  src/main/java/org/com/itpple/spot/server/exception/GlobalExceptionHandler.java
Labels: enhancement

#70 [test] 반응 관련 테스트코드 작성
  src/main/java/org/com/itpple/spot/server/domain/reaction/entity/Reaction.java
  src/test/java/org/com/itpple/spot/server/domain/reaction/repository/ReactionRepositoryTest.java
  src/test/java/org/com/itpple/spot/server/domain/reaction/service/ReactionServiceTest.java
  src/test/java/org/com/itpple/spot/server/util/PotTestUtil.java
  src/test/java/org/com/itpple/spot/server/util/ReactionTestUtil.java
  src/test/java/org/com/itpple/spot/server/util/UserTestUtil.java
Labels: test

#72 [test] 댓글 관련 테스트코드 작성
  src/test/java/org/com/itpple/spot/server/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/org/com/itpple/spot/server/domain/comment/service/CommentServiceTest.java
  src/test/java/org/com/itpple/spot/server/domain/reaction/repository/ReactionRepositoryTest.java
  src/test/java/org/com/itpple/spot/server/util/CommentTestUtil.java
  src/test/java/org/com/itpple/spot/server/util/UserTestUtil.java
Labels: test

#78 [feat] 팟 조회수 관련 로직 추가
  src/main/java/org/com/itpple/spot/server/domain/pot/api/PotController.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/viewHistory/entity/ViewHistory.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/viewHistory/repository/ViewHistoryRepository.java
  src/main/java/org/com/itpple/spot/server/domain/pot/dto/PotDTO.java
  src/main/java/org/com/itpple/spot/server/domain/pot/entity/Pot.java
  src/main/java/org/com/itpple/spot/server/domain/pot/repository/PotRepository.java
  src/main/java/org/com/itpple/spot/server/domain/pot/service/PotService.java
  src/main/java/org/com/itpple/spot/server/domain/pot/service/impl/PotServiceImpl.java
  src/test/java/org/com/itpple/spot/server/domain/pot/api/PotControllerTest.java
Labels: enhancement

#77 [feat] 해시태그 추가
  src/main/java/org/com/itpple/spot/server/domain/pot/advice/PotControllerAdvice.java
  src/main/java/org/com/itpple/spot/server/domain/pot/api/PotController.java
  src/main/java/org/com/itpple/spot/server/domain/pot/category/repository/CategoryRepository.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/category/entity/Category.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/category/repository/CategoryRepository.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/hashtag/entity/Hashtag.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/hashtag/entity/PotHashtag.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/hashtag/repository/HashtagRepository.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/hashtag/service/HashtagService.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/hashtag/service/HashtagServiceImpl.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/viewHistory/entity/ViewHistory.java
  src/main/java/org/com/itpple/spot/server/domain/pot/domain/viewHistory/repository/ViewHistoryRepository.java
  src/main/java/org/com/itpple/spot/server/domain/pot/dto/CategoryDTO.java
  src/main/java/org/com/itpple/spot/server/domain/pot/dto/HashtagDTO.java
  src/main/java/org/com/itpple/spot/server/domain/pot/dto/PotDTO.java
  src/main/java/org/com/itpple/spot/server/domain/pot/dto/SearchCondition.java
  src/main/java/org/com/itpple/spot/server/domain/pot/dto/request/CreateHashtagRequest.java
  src/main/java/org/com/itpple/spot/server/domain/pot/dto/request/CreatePotRequest.java
  src/main/java/org/com/itpple/spot/server/domain/pot/dto/response/GetCategoryResponse.java
  src/main/java/org/com/itpple/spot/server/domain/pot/entity/Pot.java
  src/main/java/org/com/itpple/spot/server/domain/pot/repository/PotRepository.java
  src/main/java/org/com/itpple/spot/server/domain/pot/service/PotService.java
  src/main/java/org/com/itpple/spot/server/domain/pot/service/impl/PotServiceImpl.java
  src/main/java/org/com/itpple/spot/server/global/exception/code/ErrorCode.java
  src/test/java/org/com/itpple/spot/server/domain/comment/repository/CommentRepositoryTest.java
  src/test/java/org/com/itpple/spot/server/domain/pot/api/PotControllerTest.java
  src/test/java/org/com/itpple/spot/server/domain/pot/repository/PotRepositoryTest.java
  src/test/java/org/com/itpple/spot/server/domain/pot/service/PotServiceTest.java
  src/test/java/org/com/itpple/spot/server/domain/reaction/repository/ReactionRepositoryTest.java
  src/test/java/org/com/itpple/spot/server/util/PotTestUtil.java
Labels: enhancement
